# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-19 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_root',
            field=models.BooleanField(default=False, verbose_name='root article'),
        ),
    ]
