branch-defaults:
  master:
    environment: wiki
    group_suffix: null
environment-defaults:
  sixcycle-wiki:
    branch: master
    repository: origin
global:
  application_name: sixcycle-wiki
  branch: null
  default_ec2_keyname: sixcycleServerKey
  default_platform: python-3.5.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
