# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-23 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0003_article_is_root'),
        ('relationships', '0003_groupsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReadArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEditArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReadArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='GroupsArticle',
            new_name='GroupEditArticle',
        ),
        migrations.RenameModel(
            old_name='OrganizationArticle',
            new_name='OrganizationEditArticle',
        ),
        migrations.RenameModel(
            old_name='UsersArticle',
            new_name='OrganizationReadArticle',
        ),
        migrations.RemoveField(
            model_name='organizationreadarticle',
            name='user',
        ),
        migrations.AddField(
            model_name='organizationreadarticle',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.Organization'),
            preserve_default=False,
        ),
    ]
