# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiextensions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article'),
        ),
    ]
